# Site Settings
title: 울림을 가진 글들

# Site Author
author:
    name: Roeniss
    bio: "This is a cool Jekyll theme, check it out!"
    email: mitchell@mitchellcash.com

# Reading Files
exclude:
    - vendor
    - .asset-cache
    - .bundle
    - .jekyll-assets-cache
    - .sass-cache
    - Gemfile
    - Gemfile.lock

# Conversion
markdown: kramdown
